/*
  lib/types.ts — Shared TypeScript Types

  TypeScript is a superset of JavaScript that adds static typing.
  Instead of just `let name = "vikram"` you can write `let name: string = "vikram"`.
  If you then accidentally do `name = 42`, TypeScript catches it as a compile-time
  error BEFORE it ever runs in a browser.

  This file defines the "shape" of data that flows through our app.
  We define it once here and import it everywhere — if the shape changes,
  TypeScript tells us every place that needs updating.

  WHY a separate `lib/` folder?
  - `app/` → pages and routing
  - `components/` → reusable UI pieces
  - `lib/` → pure logic, types, utilities (no JSX, no UI)
  This separation keeps things organized and testable.
*/

// ── Document ──────────────────────────────────────────────────────────────

/**
 * Represents an uploaded document that has been processed by the backend.
 * After a PDF is uploaded and indexed, the backend returns one of these.
 */
export interface Document {
  /** A unique ID the backend assigns to this document (e.g. "doc_abc123") */
  id: string;
  /** The original filename: "annual_report_2024.pdf" */
  name: string;
  /** Total number of pages in the PDF */
  pageCount: number;
  /** How many text chunks it was split into for the vector database */
  chunkCount: number;
  /** When it was uploaded — stored as ISO string e.g. "2024-01-15T10:30:00Z" */
  uploadedAt: string;
}

// ── Chat Messages ─────────────────────────────────────────────────────────

/**
 * A single source chunk that the backend retrieved from the vector database.
 * This is what powers citations — we can show the user exactly which
 * part of the document the AI used to answer the question.
 */
export interface SourceChunk {
  /** The actual text content of this chunk */
  content: string;
  /** Page number in the original PDF (1-indexed) */
  page: number;
  /** Similarity score 0–1. How closely this chunk matched the user's query.
   *  1.0 = identical meaning, 0.0 = completely unrelated.
   *  Scores above ~0.75 are usually good matches. */
  score: number;
}

/**
 * A single message in the chat.
 * Both user messages and AI responses are represented as Message objects.
 * The `role` field tells them apart.
 */
export interface Message {
  /** Unique ID for React's key prop (prevents re-render bugs in lists) */
  id: string;
  /** "user" = typed by the human, "assistant" = generated by the AI */
  role: "user" | "assistant";
  /** The text content of the message */
  content: string;
  /** Timestamp as ISO string */
  timestamp: string;
  /** Only present on assistant messages — the source chunks used to generate
   *  this response. This is what enables source citations in the UI. */
  sources?: SourceChunk[];
  /** True while the AI is still streaming its response token by token.
   *  The UI uses this to show a loading state for that message. */
  isStreaming?: boolean;
}

// ── API Request/Response Shapes ───────────────────────────────────────────

/**
 * What we send to POST /api/py/chat
 */
export interface ChatRequest {
  /** The user's question */
  question: string;
  /** The document ID to search within */
  documentId: string;
  /** Previous messages for conversation context (optional for MVP) */
  history?: Array<{ role: "user" | "assistant"; content: string }>;
}

/**
 * What the backend returns for the document upload endpoint.
 * POST /api/py/upload → UploadResponse
 */
export interface UploadResponse {
  success: boolean;
  document: Document;
  message: string;
}

// ── App State ─────────────────────────────────────────────────────────────

/**
 * The possible states of the ingestion pipeline.
 * We show different UI for each state so the user always knows what's happening.
 *
 * idle       → no document uploaded yet
 * uploading  → file is being sent to the server
 * processing → server is extracting text, chunking, embedding, storing in Chroma
 * ready      → document is indexed and ready to chat
 * error      → something went wrong
 */
export type IngestionStatus =
  | "idle"
  | "uploading"
  | "processing"
  | "ready"
  | "error";
